# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

permissions:
  checks: write

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:

    strategy:
      matrix:
        build_type:
        - Release
        - Debug

    name: Build ${{ matrix.build_type }}
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v4

    # ================================
    # CONFIGURE CMAKE
    # ================================
    - name: Configure CMake
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    # ================================
    # BUILD WITH CMAKE
    # ================================
    - name: Build ${{ matrix.build_type }}
      run: cmake --build ${{env.BUILD_DIR}} --config ${{ matrix.build_type }}

    # ================================
    # TEST
    # ================================
    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: ctest -C ${{ matrix.build_type }} --parallel --verbose --output-junit junit-reports/TEST-results.xml

    # ================================
    # TEST REPORT
    # ================================
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        check_name: ${{ matrix.build_type }} Test Report
        detailed_summary: true
        include_passed: true
