# Generate and publish docs to GitHub Pages
name: Docs

on:
  push:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  docs:

    permissions:
      pages: write
      id-token: write
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:

    # ================================
    # INSTALL DOXYGEN
    # ================================
    - name: Install Doxygen
      run: |
        mkdir ~/doxygen
        cd ~/doxygen
        echo "Installing latest Doxygen version"
        DOWNLOAD_URL=`curl -s https://api.github.com/repos/doxygen/doxygen/releases/latest | jq -r '.assets[].browser_download_url | select(contains("linux"))'`
        wget -nv $DOWNLOAD_URL
        tar -xf *.linux.bin.tar.gz
        rm *.linux.bin.tar.gz
        cd doxygen-*
        sudo make install

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v4

    # ================================
    # CONFIGURE CMAKE
    # ================================
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    # ================================
    # BUILD WITH CMAKE
    # ================================
    - name: Generate Doxygen docs
      run: cmake --build ${{github.workspace}}/build --config Debug --target docs

    # ================================
    # UPLOAD DOXYGEN
    # ================================
    - name: Upload Doxygen files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{github.workspace}}/build/doxygen/html

    # ================================
    # PUBLISH DOCUMENTATION
    # ================================
    - name: Publish documentation to GitHub Pages
      uses: actions/deploy-pages@v4
